### ISSUE TITLE
String literals checked for errors

### ISSUE THREAD

**Issue by dannypurcell** [vermut/intellij-ansible#13]
Thank you for releasing this for everyone! It's looking pretty good so far.

Adding the plugin on a project using DropWizard configuration files I found that the parser is checking single line string literals for syntax errors. The following snippet was taken from a working config file.
```
---
logFormat: "[%d{ISO8601}] [%p] [%t] [%logger{20}] [MDC:%mdc] %m%n"
```

**Comment by vermut** [comment]
This is also due to inefficient parser. String literals can contain {{ }} tags so I need to look for them inside. Currently it treats unquoted and double quoted strings as literals (black text) and single quoted - as string (without syntax checking). As an option, you can replace double quotes to single.

But in the future it maybe a good idea to split it into two plugins - simple YAML and Ansible. Or maybe add a toggle switch in config.

**Comment by vermut** [comment]
I made a different Yaml parser plugin. It does not include any Ansible functionality but parses YAML really good. Can you [try it](https://github.com/vermut/intellij-snakeyaml/raw/master/intellij-snakeyaml.zip) and see if it works better?

**Comment by dannypurcell** [comment]
I tried the new one out this morning, it's looking good and appears to recognized the above example correctly.

Thanks for taking the time to set up a whole new project for this!
