### ISSUE TITLE
Add documentation on how to change default *.yml & *.yaml to this module.

### ISSUE THREAD

**Issue by fubarhouse** [vermut/intellij-ansible#64]
Simply to add documentation on the readme on the importance of and how to change the default file association for *.yml & *.yaml from YAML to Ansible/YAML.

Long have I been thinking this module wasn't working until I really tried to nut it out, but now I have it working :)

**Comment by leepa** [comment]
You have it working but you might want to share how so that the documentation can be updated.

**Comment by fubarhouse** [comment]
Sure, I'll create a PR tonight.

**Comment by NicolasCharpentier** [comment]
I cannot find a way to pull request you from my fork. Here is something you may wanna try

## Configuration to enable the plugin

If the plugin doesn't look like it is working, it's probably because it reads the .yml, .yaml as `YAML`files, not as `YAML/Ansible`. To enable it do as follows :

1. Go to XXStorm → Preferences
2. Click on Editor → File Types → YAML/Ansible
3. Add the patterns `*.yaml` and `*.yml`. It will tell you that they are already used, that's right, by `YAML`, so select `Overwrite` (or something like that)

![alt tag](https://image.noelshack.com/fichiers/2017/10/1489001038-capture-d-ecran-2017-03-08-a-20-19-49.png)

**Comment by fubarhouse** [comment]
Interesting, creating a PR for a fork of a fork of the original.

I had forgotten about this, so I'll see if I can tonight - but if you couldn't create one I have my doubts that I'll be able to...

**Comment by vermut** [comment]
Cherry-picked PR manually.
